### ISSUE TITLE
多类型参数 example 生成格式不对

### ISSUE THREAD

**Issue by CatTail** [ruojs/ruo#18]
当一个参数有多个类型时，如

```yaml
type: object
properties:
  code
    type: [string, number]
    description: blablabla
```

将生成 example

```json
{
  "name": {}
}
```

**Comment by kaidiren** [comment]
https://github.com/ruojs/ruo-ui/pull/2

**Comment by kaidiren** [comment]
https://github.com/ruojs/ruo-swagger-parser/pull/1

**Comment by kaidiren** [comment]
修正后将显示为

```yaml
type: object
properties:
  code
    type: [string, number]
    description: blablabla
```

将生成 example

```json
{
  "name": "stringValue"
}
```
